### ISSUE TITLE
Crash when Tinkers Construct Scythe attacks a mob

### ISSUE THREAD

**Issue by KnightMiner** [iChun/Mob-Amputation#6]
From SlimeKnights/TinkersConstruct#3189. Original crash report: https://pastebin.com/B1NqBNXJ

**Comment by iChun** [comment]
Perfect thanks.

**Comment by Cyprex** [comment]
any update on this?

**Comment by SethMcSpazz** [comment]
I, too, have been having this issue recently.
[crash-2018-03-17_18.16.37-client.txt](https://github.com/iChun/Mob-Amputation/files/1822191/crash-2018-03-17_18.16.37-client.txt)

**Comment by Wolframme** [comment]
This crash is still a thing. https://pastebin.com/VHH839kv
